use $BASH_SOURCE instead of $0

diff --git a/usr/lib/curl-scripts/curl-prgrs b/usr/lib/curl-scripts/curl-prgrs
--- a/usr/lib/curl-scripts/curl-prgrs
+++ b/usr/lib/curl-scripts/curl-prgrs
@@ -107,7 +107,7 @@ if [ "$CURL" = "" ]; then
 fi
 
 signal_sighup() {
-   echo "INFO $0: SIGHUP received! Exiting." >&4
+   echo "INFO $BASH_SOURCE: SIGHUP received! Exiting." >&4
    shutdown
 }
 
@@ -197,7 +197,7 @@ print_progress() {
   if [ "$CURL_PRGRS_EXEC" = "" ]; then
     true
   else
-    #echo "$0 CURL_PRGRS_EXEC: $CURL_PRGRS_EXEC" >&4
+    #echo "$BASH_SOURCE CURL_PRGRS_EXEC: $CURL_PRGRS_EXEC" >&4
     eval $CURL_PRGRS_EXEC >&4
   fi
 }
@@ -247,7 +247,7 @@ unbuffered_sed \
         true
       else
         if [ "$CURL_OUT_FILE" = "" ]; then
-          echo "$0 ERROR: Variable CURL_OUT_FILE is empty." >&2
+          echo "$BASH_SOURCE ERROR: Variable CURL_OUT_FILE is empty." >&2
           error_exit_code="57"
           echo "$error_exit_code" > "$statusfile"
           shutdown
